import React, { useState } from 'react';
import ChatModal from '../ChatModal';
import './App.css';

/**
 * This component renders a demo page for the LinkedIn extension.
 * It displays a button to open the AI reply modal, and shows the inserted
 * message below the button.
 */
const App: React.FC = () => {
  // State to control the visibility of the Extension Modal
  const [isModalVisible, setModalVisibility] = useState(false);

  // State to store the generated message
  const [generatedMessage, setGeneratedMessage] = useState<string | null>(null);

  /**
   * Opens the Extension Modal.
   */
  const showModal = () => {
    setModalVisibility(true);
  };

  /**
   * Closes the Extension Modal.
   */
  const closeModal = () => {
    setModalVisibility(false);
  };

  /**
   * Insert the generated message into the page.
   * This function is passed to the Extension Modal as a prop.
   * @param {string} generatedMessage The message generated by the AI.
   */
  const insertMessage = (generatedMessage: string) => {
    setGeneratedMessage(generatedMessage);
    setModalVisibility(false);
  };

  return (
    <div className="App">

      <h2 className="font-bold mb-7 text-5xl tracking-wide text-blue-500">
        LinkedIn Extension Demo
      </h2>

      <button
        className="bg-gradient-to-r from-blue-500 to-cyan-500 text-white px-6 py-2 rounded-lg shadow-lg hover:shadow-xl transition duration-200 ease-in-out"
        onClick={showModal}
      >
        Open AI Reply Modal
      </button>

      {/* Show the Extension Modal when the button is clicked */}
      {isModalVisible && (
        <ChatModal
          onHide={closeModal}
          onInsertMessage={insertMessage} // Use the handler to insert the message
        />
      )}

      {/* Display the inserted message below */}
      {generatedMessage && (
        <div className="mt-4 p-4 border rounded bg-gray-100">
          <h2 className="text-xl font-semibold">Inserted Message:</h2>
          <p>{generatedMessage}</p>
        </div>
      )}
    </div>
  );
};

export default App;